Repository ApertureViewer/Aperture-Viewer, pull requests merged in 2025-05, with the labels that each got.

#8 Fixes: Correct default constraints in featuretable_aperture.txt
  indra/newview/featuretable_aperture.txt
Labels: bug

#12 Enhance: Default script dialog position to top-right (#11)
  indra/newview/app_settings/settings.xml
Labels: enhancement

#10 Fixes: Correct Name Tag Display functionality in Phototools floater
  indra/newview/skins/default/xui/en/floater_ap_phototools.xml
Labels: bug

#18 Docs: Add CONTRIBUTING.md file
  CONTRIBUTING.md
Labels: documentation

#21 Fixes: Default Avatar Complexity and Phototools UI Integration
  indra/newview/apfloaterphototools.cpp
  indra/newview/apfloaterphototools.h
  indra/newview/app_settings/settings.xml
  indra/newview/featuretable_aperture.txt
Labels: bug

#27 Fixes: Correct double-click action persistence and default behavior
  indra/newview/app_settings/settings.xml
  indra/newview/llfloaterpreference.cpp
Labels: bug

#29 Fixes: Standard Viewer Camera Presets Do Not Save/Restore Roll Angle
  indra/newview/apfloaterphototools.cpp
Labels: bug

#22 Translation: Japanese
  indra/newview/skins/aperture/xui/ja/floater_camera.xml
  indra/newview/skins/aperture/xui/ja/floater_preview_texture.xml
  indra/newview/skins/aperture/xui/ja/panel_edit_eyes.xml
  indra/newview/skins/aperture/xui/ja/panel_edit_gloves.xml
  indra/newview/skins/aperture/xui/ja/panel_edit_hair.xml
  indra/newview/skins/aperture/xui/ja/panel_edit_jacket.xml
  indra/newview/skins/aperture/xui/ja/panel_edit_pants.xml
  indra/newview/skins/aperture/xui/ja/panel_edit_physics.xml
  indra/newview/skins/aperture/xui/ja/panel_edit_shape.xml
  indra/newview/skins/aperture/xui/ja/panel_edit_shirt.xml
  indra/newview/skins/aperture/xui/ja/panel_edit_shoes.xml
  indra/newview/skins/aperture/xui/ja/panel_edit_skin.xml
  indra/newview/skins/aperture/xui/ja/panel_edit_skirt.xml
  indra/newview/skins/aperture/xui/ja/panel_edit_socks.xml
  indra/newview/skins/aperture/xui/ja/panel_edit_underpants.xml
  indra/newview/skins/aperture/xui/ja/panel_edit_undershirt.xml
  indra/newview/skins/aperture/xui/ja/panel_edit_wearable.xml
  indra/newview/skins/aperture/xui/ja/panel_main_inventory.xml
  indra/newview/skins/default/xui/ja/floater_about.xml
  indra/newview/skins/default/xui/ja/floater_ap_phototools.xml
  indra/newview/skins/default/xui/ja/floater_save_pref_preset.xml
  indra/newview/skins/default/xui/ja/floater_tos.xml
  indra/newview/skins/default/xui/ja/menu_login.xml
  indra/newview/skins/default/xui/ja/menu_viewer.xml
  indra/newview/skins/default/xui/ja/panel_preferences_colors.xml
  indra/newview/skins/default/xui/ja/panel_preferences_graphics1.xml
  indra/newview/skins/default/xui/ja/panel_preferences_setup.xml
  scripts/code_tools/fix_xml_indentations.py
  scripts/code_tools/modified-strings.sh
  scripts/code_tools/modified_strings.py
Labels: enhancement

#24 [FEAT] Override Default Add friend, Teleport Messages
  indra/newview/app_settings/settings_per_account.xml
  indra/newview/llavataractions.cpp
  indra/newview/llfloaterpreference.cpp
  indra/newview/llfloaterpreference.h
  indra/newview/llviewermessage.cpp
  indra/newview/skins/default/xui/en/notifications.xml
  indra/newview/skins/default/xui/en/panel_preferences_override.xml
  indra/newview/skins/default/xui/en/panel_preferences_privacy.xml
  indra/newview/skins/default/xui/en/strings.xml
Labels: enhancement

#44 Hotfix: Consolidated UI, Defaults, and Configuration Tweaks (Batch 1)
  indra/newview/apfloaterphototools.cpp
  indra/newview/apfloaterphototools.h
  indra/newview/app_settings/settings.xml
  indra/newview/app_settings/settings_firestorm.xml
  indra/newview/app_settings/settings_phoenix.xml
  indra/newview/app_settings/settings_text.xml
  indra/newview/featuretable_aperture.txt
  indra/newview/llfeaturemanager.cpp
  indra/newview/skins/default/xui/en/floater_ap_phototools.xml
  indra/newview/skins/default/xui/en/panel_preferences_graphics1.xml
Labels: hotfix
